language: php

addons:
  apt:
    packages:
      - parallel
  sonarcloud:
    organization: "ichhabrecht-github"
    branches:
      - master
      - pre-merge

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.sonar/cache

jdk:
  - oraclejdk8

sudo: required

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - >
    if [[ "$TYPO3" = *"dev"* ]]; then
      composer config minimum-stability dev;
      composer config prefer-stable true;
      composer require typo3/cms-core="dev-master" --no-update;
      composer require typo3/cms-extbase="dev-master" --no-update;
    fi
  - composer require nimut/typo3-complete="$TYPO3"
  - export TYPO3_PATH_ROOT=$PWD/.Build/Web

script:
   - >
     echo;
     echo "Running unit tests";
     echo;
     echo;
     .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/;

   - >
     echo;
     echo "Running php lint";
     echo;
     echo;
     find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;;

jobs:
  fast_finish: true
  allow_failures:
    - env: TYPO3=dev-master
  include:
    - stage: test
      php: 7.2
      env: TYPO3=dev-master
    - stage: test
      php: 7.2
      env: TYPO3=~9.2.0
    - stage: test
      php: 7.2
      env: TYPO3=~9.1.1
    - stage: test
      php: 7.2
      env: TYPO3=~9.0.2
    - stage: test
      php: 7.2
      env: TYPO3=^8.7
    - stage: test
      php: 7.1
      env: TYPO3=^8.7
    - stage: test
      php: 7.1
      env: TYPO3=^7.6
    - stage: test
      php: 7.0
      env: TYPO3=^8.0
    - stage: test
      php: 7.0
      env: TYPO3=^7.6
    - stage: test
      php: 5.6
      env: TYPO3=^7.6
    - stage: test
      php: 5.5
      env: TYPO3=^7.6

    - stage: publish to ter
      if: tag IS present
      php: 7.0
      before_install: skip
      install: skip
      before_script: skip
      script:
        - >
          if [ -n "$TYPO3_ORG_USERNAME" ] && [ -n "$TYPO3_ORG_PASSWORD" ]; then
            echo;
            echo "Preparing upload of release ${TRAVIS_TAG} to TER";
            echo;
            echo;
            composer install --no-dev;
            composer require --update-no-dev helhum/ter-client dev-master;

            # Cleanup before we upload
            git reset --hard HEAD && git clean -fx;

            # Upload
            TAG_MESSAGE=`git tag -n10 -l $TRAVIS_TAG | sed 's/^[0-9.]*[ ]*//g'`;
            echo;
            echo "Uploading release ${TRAVIS_TAG} to TER";
            echo;
            echo;
            .Build/bin/ter-client upload hosts_pattern . -u "$TYPO3_ORG_USERNAME" -p "$TYPO3_ORG_PASSWORD" -m "$TAG_MESSAGE";
          fi

    - stage: sonarqube scanner
      if: type = push AND branch IN (master, pre-merge)
      php: 7.2
      env: TYPO3=^9.0
      before_install: skip
      install:
        - composer require nimut/typo3-complete="$TYPO3"
        - mkdir -p .Build/Web/typo3conf/ext/ .Log/coverage/ .Log/log/
        - export TYPO3_PATH_ROOT=$PWD/.Build/Web
      before_script:
      script:
        - >
          echo;
          echo "Running unit tests";
          echo;
          echo;
          .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml --log-junit .Log/log/functional.xml --coverage-php .Log/coverage/functional.cov --whitelist Classes Tests/Unit/;

        - >
          echo;
          echo "Merging log and coverage files";
          echo;
          echo;
          composer require --update-with-all-dependencies nimut/phpunit-merger;
          .Build/bin/phpunit-merger coverage .Log/coverage/ .Log/coverage.xml;
          .Build/bin/phpunit-merger log .Log/log/ .Log/log.xml;

        - git fetch --unshallow || true

        - >
          echo;
          echo "Running SonarQube Scanner";
          echo;
          echo;
          sonar-scanner;
