language: php

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

sudo: false

before_install:
  - if php -i | grep -q xdebug; then phpenv config-rm xdebug.ini; fi

install:
  - composer require typo3/cms="$TYPO3"
  - export TYPO3_PATH_ROOT=$PWD/.Build/Web

script:
   - >
     echo;
     echo "Running unit tests";
     echo;
     echo;
     .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/

   - >
     echo;
     echo "Running php lint";
     echo;
     echo;
     find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;

jobs:
  fast_finish: true
  include:
      - stage: test
        php: 7.2
        env: TYPO3=^8.0
      - stage: test
        php: 7.1
        env: TYPO3=^8.0
      - stage: test
        php: 7.1
        env: TYPO3=^7.6
      - stage: test
        php: 7.0
        env: TYPO3=^8.0
      - stage: test
        php: 7.0
        env: TYPO3=^7.6
      - stage: test
        php: 5.6
        env: TYPO3=^7.6
      - stage: test
        php: 5.5
        env: TYPO3=^7.6
